#+TITLE: Computer Networks
#+SUBTITLE: Lab 1
#+AUTHOR: Seshal Jain
#+OPTIONS: num:nil toc:nil ^:nil
#+DATE: January 10, 2022
#+LATEX_CLASS: assignment
#+LATEX_HEADER: \definecolor{solarized-bg}{HTML}{fdf6e3}
#+EXPORT_FILE_NAME: 191112436

* Types of Network Cables
There are 3 types of network cables primarily:
- *Co-axial network cables* \\
  These cables are highly resistant to obstruction and work for long lengths of
  wire. However, they are complex to install.

  They are further divided into:
  + Single core: made of single copper conductor
  + Multi core: made of multiple strands

  The structure of co-axial cables consists of the following (in order from
  center):
  + Conductor: carries the EM signals
  + Insulation: protects from interference and noise
  + Braiding: protects from interference and noise
  + Sheath: protects from physical damage

- *Fibre optic cables* \\
  These are super fast cables, capable of carrying signals at speeds of over
  100GBPS over almost 40km distance.

  These are divided into:
  + Single mode: carries only single beam of light. Higher bandwidth, but supports higher distance
  + Multi mode: carries multiple beams of light. Higher speed, but supports shorter distance

  The structure of fiber optic cable consists of the following (in order from
  center):
  + Core: carries light signals
  + Cladding: reflects light back into core
  + Buffer protects light from leaking
  + Jacket: prevents physical damage

- *Twisted pair cable* \\
  This is also known as Ethernet cable.  It consists of 4 color-coded insulated
  copper wire pairs

  It has 2 types: UTP (unshielded twisted pair cable), and STP (shielded twisted
  pair cable)

  + It can transmit at speed ranging from 10MBPS - 10 GBPS
  + STP is expensive (more material for shielding)
  + STP gives more noise, and EMI resistance
  + Max segment length is 100m

* Types of Networking Devices
Common network devices are:
- *Hub* \\
  Hub connects multiple deices together. It also acts as repeater and amplifies
  the signal. They do not perform address functions or packet filtering, only
  forwarding it to all devices. It has 2 types - single port and multi port.
- *Switch* \\
  It maintains limited routing information about internal network nodes. Strands
  of LAN are usually connected through switch. They improve the network
  efficiency and security. In can work as the /data link/ or /network layer/ of
  OSI model.
- *Router* \\
  Routers transmit packets to their destination through interconnected networks
  using different network topologies. Routers maintain tables about destinations
  and local connections and communicate using /Routing Information Protocol/,
  /Border Gateway Protocol/ and /Open Shortest Path First Protocol/
- *Bridge* \\
  Bridge is used to connect two or more network segments together. Bridges
  store and forward frames between different segments connected by them. They
  work at the /physical/ & /data link/ layer of OSI model. Modern switches,
  called multiport brides have replaced bridges.
- *Gateway* \\
  They work at the /transport/ & /session/ layer of OSI model. It provides
  translation between technologies like OSI and TCP/IP. It performs all the
  functions of router, it is basically a router with translation functionality.
- *Modem* \\
  Modems, or /modulator-demodulator/ are used to transmit digital signal over
  telephone lines. It converts digital signal to analog over different
  frequencies and transmits to modem at receiver station. They work on both
  /physical/ and /data link/ layer.
- *Repeater* \\
  Repeater is an analog device which receives a signal and transmits it at
  higher level or power so that the signal can cover greater lengths. It works
  on the /physical/ layer.
* Types of Network Topologies
Different types of network topologies are:
- *Bus Topology* \\
  Every device on a network is connected to solo main cable line. Data is
  transmitted in single route, from one point to another.

  *Benefit*: cost effective, least cable length required \\
  *Drawback*: entire network fails if main cable collapses, lower performance
  with multiple nodes
- *Ring Topology* \\
  Each computer is connected together with other computers on both sides,
  forming a ring-like shape. Data is transmitted in sequential mode, i.e. bit by
  bit, and routes through each node in the network.

  *Benefit*: cheap installation and expansion, not affected by heavy traffic \\
  *Drawback*: difficult to troubleshoot, difficult to add/delete nodes
- *Star Topology* \\
  All nodes are connected to a single node called hub, which can be active or
  passive.

  *Benefit*: fast performance, due to low traffic, easy to troubleshoot &
  upgrade \\
  *Drawbacks*: high installation cost, all nodes dependent on hub
- *Mesh Topology* \\
  All nodes are connected to *all* other nodes. It is a point to point
  connection, and requires $\frac{n \times (n-1)}{2}$ network channels to
  connect =n= nodes. It uses rounding and flooding technique for transmission.

  *Benefit*: very robust, easy to diagnose fault, provides privacy and security
  \\
  *Drawback*: challenging to install, configuration is difficult, cable cost is
  very high
- *Tree Topology* \\
  All nodes are connected hierarchically to the root node. It is used mostly in
  WAN and is an extension of /star/ and /bus/ topology.

  *Benefit*: easy to expand network, easy to detect and troubleshoot errors \\
  *Drawback*: expensive to other technologies, entire networks collapses if root
  node fails
- *Hybrid Topology* \\
  It comprises of two or more different topologies and has the merits and
  demerits of all the topologies used.

  *Benefit*: flexible, durable \\
  *Drawback*: difficult to design
